os:              osx
osx_image:       xcode10.2
env:
    - ENV=CI

before_install:
    - brew unlink python
    - brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/f2a764ef944b1080be64bd88dca9a1d80130c558/Formula/python.rb
    - python3 -V
    - python -V
    - git clone https://${GIT_VAR}@git.bio-feed.org/BioFeed/plants-data dataset
install:
    - pip3 install -U coremltools
    - pip3 install -r requirements.txt

script:
    - python3 test.py
    - ls -lah

notifications:
    email:       false
